A numerical method for solving systems of linear equations known as the Gauss method.

In [45]:
# Connection libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import scipy as sp
import scipy.linalg as la
import sympy as sym
from sympy import *
from sympy import init_printing
init_printing(use_latex='mathjax') # Latex output

In [50]:
# Definition of input data
N = 3 # number of equations
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]]) # coefficient matrix
b = np.array([1, 2, 3]) # right-hand side vector

Task: Solve the system of linear equations $Ax=b$.
\begin{equation*}
    A = 
    \begin{bmatrix}
        1 & 2 & 3 \\
        4 & 5 & 6 \\
        7 & 8 & 10
    \end{bmatrix}, \quad
    b = 
    \begin{bmatrix}
        1 \\
        2 \\
        3
    \end{bmatrix}
\end{equation*}

In [52]:
# Gaussian elimination
def gauss_elim(A, b):
    # Forward elimination
    for k in range(N-1):
        for i in range(k+1, N):
            if A[i, k] != 0.0:
                lam = A[i, k]/A[k, k]
                A[i, k+1:N] = A[i, k+1:N] - lam*A[k, k+1:N]
                b[i] = b[i] - lam*b[k]
    # Back substitution
    for k in range(N-1, -1, -1):
        b[k] = (b[k] - np.dot(A[k, k+1:N], b[k+1:N]))/A[k, k]
    return b

In [69]:
# Output
print(A, b)
print('Solution of linear equations: ', gauss_elim(A.copy(), b.copy()))
print('Solution of linear equations using numpy: ', np.linalg.solve(A, b))

[[   1    2    3]
 [   4 -123 -186]
 [   7 -216 2371]] [1 0 0]
Solution of linear equations:  [1 0 0]
Solution of linear equations using numpy:  [9.42446196e-01 2.87662687e-02 7.08877988e-06]
