A numerical method for solving systems of linear equations known as the Gauss method.

In [45]:
# Connection libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import scipy as sp
import scipy.linalg as la
import sympy as sym
from sympy import *
from sympy import init_printing
init_printing(use_latex='mathjax') # Latex output

In [183]:
# Definition of input data
N = 3 # number of equations
A = np.array([[1, 1, 1], [2, 2, 3], [3, 4, 5]]) # coefficient matrix
b = np.array([2, 3, 5]) # right-hand side vector

Task: Solve the system of linear equations $Ax=b$.
\begin{equation*}
    A = 
    \begin{bmatrix}
        1 & 2 & 3 \\
        4 & 5 & 6 \\
        7 & 8 & 10
    \end{bmatrix}, \quad
    b = 
    \begin{bmatrix}
        1 \\
        2 \\
        3
    \end{bmatrix}
\end{equation*}

In [184]:
# Gaussian elimination without changing the input data
def gauss_elim(A, b):
    # Initialization
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    N = len(b)
    # Forward elimination
    for k in range(N-1):
        for i in range(k+1, N):
            if A[i, k] != 0.0:
                lam = A[i, k]/A[k, k]
                A[i, k+1:N] = A[i, k+1:N] - lam*A[k, k+1:N]
                b[i] = b[i] - lam*b[k]
    # Back substitution
    for k in range(N-1, -1, -1):
        b[k] = (b[k] - np.dot(A[k, k+1:N], b[k+1:N]))/A[k, k]
    return b

In [185]:
# Gaussian elimination with the choice of the pivot with the largest absolute value without changing the input data
def gauss_elim_pivot(A, b):
    # Initialization
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    N = len(b)
    # Forward elimination
    for k in range(N-1):
        # Search the pivot
        p = np.argmax(np.abs(A[k:N, k])) + k
        if A[p, k] == 0:
            print('Matrix is singular!')
            return
        # Change the rows
        if p != k:
            A[[k, p]] = A[[p, k]]
            b[[k, p]] = b[[p, k]]
        # Elimination
        for i in range(k+1, N):
            if A[i, k] != 0.0:
                lam = A[i, k]/A[k, k]
                A[i, k+1:N] = A[i, k+1:N] - lam*A[k, k+1:N]
                b[i] = b[i] - lam*b[k]
    # Back substitution
    for k in range(N-1, -1, -1):
        b[k] = (b[k] - np.dot(A[k, k+1:N], b[k+1:N]))/A[k, k]
    return b

In [186]:
# Output
print(A, b)
print('Solution of the system of linear equations by Gaussian elimination: ', gauss_elim(A, b))
print('Solution of the system of linear equations by Gaussian elimination with the choice of the pivot: ', gauss_elim_pivot(A, b))
print('Solution of linear equations using numpy: ', np.linalg.solve(A, b))

[[1 1 1]
 [2 2 3]
 [3 4 5]] [2 3 5]
Solution of the system of linear equations by Gaussian elimination:  [nan nan nan]
Solution of the system of linear equations by Gaussian elimination with the choice of the pivot:  [ 2.  1. -1.]
Solution of linear equations using numpy:  [ 2.  1. -1.]


C:\Users\stas2\AppData\Local\Temp\ipykernel_16168\2450353070.py:11: RuntimeWarning: divide by zero encountered in double_scalars
  lam = A[i, k]/A[k, k]
C:\Users\stas2\AppData\Local\Temp\ipykernel_16168\2450353070.py:16: RuntimeWarning: invalid value encountered in double_scalars
  b[k] = (b[k] - np.dot(A[k, k+1:N], b[k+1:N]))/A[k, k]
